//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShipGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleShipGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Code: {0}.
        /// </summary>
        internal static string Program_Main_Error_Code___0_ {
            get {
                return ResourceManager.GetString("Program_Main_Error_Code___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading from input file.
        /// </summary>
        internal static string Program_Main_Error_reading_from_input_file {
            get {
                return ResourceManager.GetString("Program_Main_Error_reading_from_input_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating game elements.
        /// </summary>
        internal static string Program_Main_Validation_Errors {
            get {
                return ResourceManager.GetString("Program_Main_Validation_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game has ended in draw.
        /// </summary>
        internal static string Startup_InitiatePlay_Game_has_ended_in_draw {
            get {
                return ResourceManager.GetString("Startup_InitiatePlay_Game_has_ended_in_draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-1 fires a missile with target {0} which got hit.
        /// </summary>
        internal static string Startup_Player1Fire_Player_1_fires_a_missile_with_target__0__which_got_hit {
            get {
                return ResourceManager.GetString("Startup_Player1Fire_Player_1_fires_a_missile_with_target__0__which_got_hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-1 fires a missile with target {0} which got miss.
        /// </summary>
        internal static string Startup_Player1Fire_Player_1_fires_a_missile_with_target__0__which_got_miss {
            get {
                return ResourceManager.GetString("Startup_Player1Fire_Player_1_fires_a_missile_with_target__0__which_got_miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-1 has no more missiles left to launch.
        /// </summary>
        internal static string Startup_Player1Fire_Player_1_has_no_more_missiles_left_to_launch {
            get {
                return ResourceManager.GetString("Startup_Player1Fire_Player_1_has_no_more_missiles_left_to_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-1 won the battle.
        /// </summary>
        internal static string Startup_Player1Fire_Player_1_won_the_battle {
            get {
                return ResourceManager.GetString("Startup_Player1Fire_Player_1_won_the_battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-2 fires a missile with target {0} which got hit.
        /// </summary>
        internal static string Startup_Player2Fire_Player_2_fires_a_missile_with_target__0__which_got_hit {
            get {
                return ResourceManager.GetString("Startup_Player2Fire_Player_2_fires_a_missile_with_target__0__which_got_hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-2 fires a missile with target {0} which got miss.
        /// </summary>
        internal static string Startup_Player2Fire_Player_2_fires_a_missile_with_target__0__which_got_miss {
            get {
                return ResourceManager.GetString("Startup_Player2Fire_Player_2_fires_a_missile_with_target__0__which_got_miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-2 has no more missiles left to launch.
        /// </summary>
        internal static string Startup_Player2Fire_Player_2_has_no_more_missiles_left_to_launch {
            get {
                return ResourceManager.GetString("Startup_Player2Fire_Player_2_has_no_more_missiles_left_to_launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player-2 won the battle.
        /// </summary>
        internal static string Startup_Player2Fire_Player_2_won_the_battle {
            get {
                return ResourceManager.GetString("Startup_Player2Fire_Player_2_won_the_battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid input file found at : {0}.
        /// </summary>
        internal static string Startup_ReadInput_No_valid_input_file_found_at____0_ {
            get {
                return ResourceManager.GetString("Startup_ReadInput_No_valid_input_file_found_at____0_", resourceCulture);
            }
        }
    }
}
